"""create initial persistence schema

Revision ID: 665c808f8308
Revises:
Create Date: 2026-07-19 12:21:39.447380
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "665c808f8308"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beverages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("default_keg_size_ml", sa.Integer(), nullable=False),
        sa.Column("price_per_liter_cents", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("default_keg_size_ml > 0", name="ck_beverages_keg_size_positive"),
        sa.CheckConstraint("price_per_liter_cents >= 0", name="ck_beverages_price_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("year >= 2000 AND year <= 9999", name="ck_events_year"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "year", name="uq_events_name_year"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            "uq_events_single_active", ["active"], unique=True, sqlite_where=sa.text("active = 1")
        )

    op.create_table(
        "technical_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("technical_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_technical_events_event_type"), ["event_type"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="user_role", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("special_portion_ml", sa.Integer(), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "special_portion_ml IS NULL OR special_portion_ml > 0",
            name="ck_users_special_portion_positive",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "admin_audit_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=True),
        sa.Column("old_values_json", sa.Text(), nullable=True),
        sa.Column("new_values_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["admin_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kegs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("beverage_id", sa.Integer(), nullable=False),
        sa.Column("initial_volume_ml", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("initial_volume_ml > 0", name="ck_kegs_initial_volume_positive"),
        sa.ForeignKeyConstraint(["beverage_id"], ["beverages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kegs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kegs_beverage_id"), ["beverage_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kegs_event_id"), ["event_id"], unique=False)
        batch_op.create_index(
            "uq_kegs_single_active", ["active"], unique=True, sqlite_where=sa.text("active = 1")
        )

    op.create_table(
        "nfc_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    with op.batch_alter_table("nfc_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nfc_cards_user_id"), ["user_id"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tap_bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("beverage_id", sa.Integer(), nullable=False),
        sa.Column("keg_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_volume_ml", sa.Integer(), nullable=True),
        sa.Column("measured_volume_ml", sa.Integer(), nullable=False),
        sa.Column("measured_pulses", sa.Integer(), nullable=False),
        sa.Column("price_per_liter_cents", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "portion",
                "top_up",
                "maintenance",
                "free_admin",
                name="booking_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "completion",
            sa.Enum(
                "target_reached",
                "user_abort",
                "released",
                "limit_reached",
                "fault",
                "shutdown",
                name="booking_completion",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("chargeable", sa.Boolean(), nullable=False),
        sa.CheckConstraint("amount_cents >= 0", name="ck_tap_bookings_amount_nonnegative"),
        sa.CheckConstraint(
            "chargeable = 1 OR amount_cents = 0", name="ck_tap_bookings_free_amount_zero"
        ),
        sa.CheckConstraint(
            "kind != 'maintenance' OR chargeable = 0",
            name="ck_tap_bookings_maintenance_not_chargeable",
        ),
        sa.CheckConstraint("measured_pulses >= 0", name="ck_tap_bookings_pulses_nonnegative"),
        sa.CheckConstraint("measured_volume_ml >= 0", name="ck_tap_bookings_volume_nonnegative"),
        sa.CheckConstraint("price_per_liter_cents >= 0", name="ck_tap_bookings_price_nonnegative"),
        sa.CheckConstraint(
            "target_volume_ml IS NULL OR target_volume_ml > 0",
            name="ck_tap_bookings_target_positive",
        ),
        sa.ForeignKeyConstraint(["beverage_id"], ["beverages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["keg_id"], ["kegs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tap_bookings", schema=None) as batch_op:
        batch_op.create_index("ix_tap_bookings_event_user", ["event_id", "user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tap_bookings_keg_id"), ["keg_id"], unique=False)

    op.execute(
        """
        CREATE TRIGGER tap_bookings_prevent_update
        BEFORE UPDATE ON tap_bookings
        BEGIN
            SELECT RAISE(ABORT, 'completed tap bookings are immutable');
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER tap_bookings_prevent_delete
        BEFORE DELETE ON tap_bookings
        BEGIN
            SELECT RAISE(ABORT, 'completed tap bookings are immutable');
        END
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tap_bookings_prevent_delete")
    op.execute("DROP TRIGGER IF EXISTS tap_bookings_prevent_update")
    with op.batch_alter_table("tap_bookings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tap_bookings_keg_id"))
        batch_op.drop_index("ix_tap_bookings_event_user")

    op.drop_table("tap_bookings")
    op.drop_table("settings")
    with op.batch_alter_table("nfc_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nfc_cards_user_id"))

    op.drop_table("nfc_cards")
    with op.batch_alter_table("kegs", schema=None) as batch_op:
        batch_op.drop_index("uq_kegs_single_active", sqlite_where=sa.text("active = 1"))
        batch_op.drop_index(batch_op.f("ix_kegs_event_id"))
        batch_op.drop_index(batch_op.f("ix_kegs_beverage_id"))

    op.drop_table("kegs")
    op.drop_table("admin_audit_entries")
    op.drop_table("users")
    with op.batch_alter_table("technical_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technical_events_event_type"))

    op.drop_table("technical_events")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("uq_events_single_active", sqlite_where=sa.text("active = 1"))

    op.drop_table("events")
    op.drop_table("beverages")
    # ### end Alembic commands ###
